# Generated by Django 4.2.20 on 2025-04-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Category Name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description', max_length=50, null=True)),
                ('lft', models.IntegerField(default=0)),
                ('rgt', models.IntegerField()),
                ('level', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['title'],
            },
        ),
    ]
