# Generated by Django 4.2.20 on 2025-04-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='rgt',
            field=models.IntegerField(default=0),
        ),
    ]
