# Generated by Django 4.2.20 on 2025-04-24 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_alter_category_level_alter_category_rgt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tag Name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title', max_length=200)),
                ('body', models.TextField(help_text='Blog body', max_length=20000)),
                ('synopsis', models.TextField(blank=True, help_text='Synopsis', max_length=20000, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBISHED', 'Published')], help_text='Status', max_length=10)),
                ('start_time', models.TimeField(db_index=True, help_text='Optional Start time')),
                ('end_time', models.TimeField(db_index=True, help_text='Optional end time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(help_text='Categories', to='pages.category')),
                ('tags', models.ManyToManyField(help_text='Tags', to='pages.tag')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['title', '-updated'],
            },
        ),
    ]
