# Generated by Django 4.2.20 on 2025-04-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_blogpost_options_alter_blogpost_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PUBISHED', 'Published')], help_text='Status', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags', null=True, to='pages.tag'),
        ),
    ]
