# Generated by Django 4.2.20 on 2025-04-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_blogpost_status_alter_blogpost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Optional end time', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='start_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Optional Start time', null=True),
        ),
    ]
