# Generated by Django 4.2.20 on 2025-04-26 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0006_alter_blogpost_end_time_alter_blogpost_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title', max_length=200)),
                ('body', models.TextField(help_text='Blog body', max_length=20000)),
                ('synopsis', models.TextField(blank=True, help_text='Synopsis', max_length=20000, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PUBISHED', 'Published')], help_text='Status', max_length=10, null=True)),
                ('feature_image', models.ImageField(upload_to='')),
                ('lft', models.IntegerField()),
                ('rgt', models.IntegerField()),
                ('level', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.webpage')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['title', '-updated'],
            },
        ),
    ]
