# Generated by Django 4.2.20 on 2025-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_blogpost_feature_image_webpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webpage',
            options={'ordering': ['title', '-updated'], 'verbose_name': 'Web page', 'verbose_name_plural': 'Web pages'},
        ),
        migrations.AlterField(
            model_name='webpage',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='lft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='rgt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
