# Generated by Django 4.2.20 on 2025-04-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_webpage_options_alter_webpage_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='feature_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
