# Generated by Django 4.2.20 on 2025-04-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_webpage_feature_image_alter_webpage_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='priority',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
