# Generated by Django 4.2.20 on 2025-05-01 19:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_webpage_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='body',
            field=ckeditor.fields.RichTextField(help_text='Blog body', max_length=20000),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
