# Generated by Django 4.2.20 on 2025-05-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_webpage_body_alter_webpage_feature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='body',
        ),
    ]
