# Generated by Django 4.2.20 on 2025-05-01 20:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_webpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Blog body', max_length=20000, null=True),
        ),
    ]
