# Generated by Django 4.2.20 on 2025-05-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_webpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Snippet title', max_length=100)),
                ('snippet', models.TextField(help_text='Code Snippet', max_length=20000)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Code Snippet',
                'ordering': ['title', '-updated'],
            },
        ),
    ]
