# Generated by Django 4.2.20 on 2025-05-07 15:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_codesnippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', help_text='Blog body', max_length=20000),
            preserve_default=False,
        ),
    ]
