# Generated by Django 4.2.20 on 2025-05-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_webpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='type',
            field=models.CharField(choices=[('PAGE', 'Page'), ('T&C', 'Terms & Conditions'), ('PRIVACY', 'Privacy')], default='PAGE', max_length=7),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], help_text='Status', max_length=10, null=True),
        ),
    ]
