# Generated by Django 4.2.20 on 2025-05-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_blogpost_type_alter_blogpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='type',
            field=models.CharField(choices=[('PAGE', 'Page'), ('T&C', 'Terms & Conditions'), ('PRIVACY', 'Privacy Policy')], default='PAGE', help_text='Page Type', max_length=8),
        ),
    ]
