# Generated by Django 4.2.20 on 2025-05-13 19:09

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_webpage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(help_text='Tags', to='pages.tag'),
        ),
        migrations.CreateModel(
            name='BlogSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog Series title', max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Blog series description', max_length=20000, null=True)),
                ('blogpost', models.ManyToManyField(through='pages.BlogPostSeries', to='pages.blogpost')),
            ],
        ),
        migrations.AddField(
            model_name='blogpostseries',
            name='blogpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.blogpost'),
        ),
        migrations.AddField(
            model_name='blogpostseries',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.blogseries'),
        ),
        migrations.AddConstraint(
            model_name='blogpostseries',
            constraint=models.UniqueConstraint(fields=('blogpost', 'series'), name='unique_blogpost_series'),
        ),
    ]
