# Generated by Django 4.2.20 on 2025-05-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_blogpostseries_alter_blogpost_tags_blogseries_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostseries',
            options={'verbose_name': 'Blog Post Series', 'verbose_name_plural': 'Blog Post Series Entries'},
        ),
        migrations.AlterModelOptions(
            name='blogseries',
            options={'verbose_name': 'Blog Series', 'verbose_name_plural': 'Blog Series'},
        ),
        migrations.AddConstraint(
            model_name='blogpostseries',
            constraint=models.UniqueConstraint(fields=('series', 'priority'), name='unique_series_priority'),
        ),
    ]
