# Generated by Django 4.2.20 on 2025-06-17 19:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_blogpostseries_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Blog body', max_length=20000),
        ),
    ]
