# Generated by Django 4.2.20 on 2025-05-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Country Name', max_length=30, unique=True),
        ),
    ]
