# Generated by Django 4.2.20 on 2025-05-24 15:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinance', '0003_index_industry_alter_country_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company Name', max_length=50, unique=True)),
                ('symbol', models.CharField(help_text='Company Symbol', max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Too short'), django.core.validators.MaxLengthValidator(6, 'Too Long')])),
                ('symbol_yahoo', models.CharField(blank=True, help_text='Yahoo symbol', max_length=8, null=True)),
                ('symbol_google', models.CharField(blank=True, help_text='Google symbol', max_length=8, null=True)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'Sterling')], max_length=3)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prices_updated', models.DateTimeField(blank=True, help_text='Last Time Prices were updated', null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=1)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgfinance.country')),
                ('index', models.ManyToManyField(help_text='Indices', to='pgfinance.index')),
                ('industry', models.ManyToManyField(help_text='Industries', to='pgfinance.industry')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table_comment': 'Companies',
                'ordering': [],
            },
        ),
    ]
