# Generated by Django 4.2.20 on 2025-05-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinance', '0004_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='company',
            name='symbol_google',
        ),
        migrations.RemoveField(
            model_name='company',
            name='symbol_yahoo',
        ),
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_yahoo', models.CharField(help_text='Data source', max_length=8)),
                ('symbol_google', models.CharField(help_text='Google symbol', max_length=8)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'Sterling')], max_length=3)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgfinance.company')),
            ],
            options={
                'verbose_name': 'Data lookup',
                'verbose_name_plural': 'Data lookups',
                'ordering': ['company'],
                'unique_together': {('company', 'symbol_yahoo'), ('company', 'symbol_google')},
            },
        ),
    ]
