# Generated by Django 4.2.20 on 2025-05-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinance', '0005_remove_company_currency_remove_company_symbol_google_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(db_index=True, help_text='Index Name', max_length=30, unique=True),
        ),
    ]
