# Generated by Django 4.2.20 on 2025-05-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinance', '0006_alter_index_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookup',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'Sterling')], db_index=True, help_text='Currency Code', max_length=3),
        ),
    ]
