# Generated by Django 4.2.20 on 2025-05-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinance', '0007_alter_lookup_currency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lookup',
            unique_together={('company', 'symbol_google', 'currency'), ('company', 'symbol_yahoo', 'currency')},
        ),
    ]
