# Generated by Django 4.2.20 on 2025-05-27 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinance', '0008_alter_lookup_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_time', models.DateTimeField(help_text='Price Time')),
                ('period', models.CharField(default='D', help_text='Period', max_length=1)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('dividends', models.FloatField()),
                ('stock_splits', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgfinance.company')),
            ],
            options={
                'verbose_name': 'Data lookup',
                'verbose_name_plural': 'Data lookups',
                'ordering': ['company', 'price_time'],
                'index_together': {('company', 'price_time')},
            },
        ),
    ]
