# Generated by Django 4.2.20 on 2025-06-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinance', '0009_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['company', 'price_time'], 'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterIndexTogether(
            name='price',
            index_together=set(),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='symbol_google',
            field=models.CharField(help_text='Google symbol', max_length=20),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='symbol_yahoo',
            field=models.CharField(help_text='Data source', max_length=20),
        ),
    ]
