# Generated by Django 4.2.20 on 2025-06-05 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinance', '0010_alter_price_options_alter_price_index_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='lookup',
            field=models.ForeignKey(limit_choices_to={'company': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgfinance.company')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='pgfinance.lookup'),
        ),
    ]
