# Generated by Django 4.2.20 on 2025-06-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinance', '0011_price_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='lookup',
            field=models.ForeignKey(limit_choices_to={'company': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgfinance.company')}, on_delete=django.db.models.deletion.CASCADE, to='pgfinance.lookup'),
        ),
    ]
