# Generated by Django 4.2.20 on 2025-06-09 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinance', '0012_alter_price_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='dividends',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='lookup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgfinance.lookup'),
        ),
        migrations.AlterField(
            model_name='price',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='stock_splits',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
