# Generated by Django 4.2.7 on 2023-11-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_button_homepage_banner_background_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='Button',
            new_name='button',
        ),
    ]
