# Generated by Django 4.2.7 on 2023-12-26 17:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_lead_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body_stream',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(help_text='Text to display', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
