# Generated by Django 4.2.7 on 2024-01-25 20:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepage_body_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body_stream',
            field=wagtail.fields.StreamField([('blog_posts', wagtail.snippets.blocks.SnippetChooserBlock(target_model='blog.BlogPost')), ('title', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(help_text='Text to display', required=True))])), ('cards', wagtail.blocks.StructBlock([('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Bold title text (max 100)', max_length=100)), ('text', wagtail.blocks.TextBlock(help_text='Optional text, max 255', max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image will be cropped to 570px x 370px'))])))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
